#http://docs.projectcalico.org/v2.2/getting-started/kubernetes/installation/hosted/hosted
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  etcd_endpoints: "https://10.1.11.120:2379,https://10.1.11.121:2379,https://10.1.11.122:2379"
  calico_backend: "bird"
  etcd_ca:   "/calico-secrets/etcd-ca"
  etcd_cert:  "/calico-secrets/etcd-cert"
  etcd_key:  "/calico-secrets/etcd-key"
  cni_network_config: |-
      {
        "name": "k8s-pod-network",
        "cniVersion": "0.1.0",
        "type": "calico",
        "etcd_endpoints": "__ETCD_ENDPOINTS__",
        "etcd_key_file": "__ETCD_KEY_FILE__",
        "etcd_cert_file": "__ETCD_CERT_FILE__",
        "etcd_ca_cert_file": "__ETCD_CA_CERT_FILE__",
        "log_level": "info",
        "ipam": {
            "type": "calico-ipam"
        },
        "policy": {
            "type": "k8s",
            "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
            "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
        },
        "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
        }
      }
