# author:pengrk
# email:546711211@qq.com
# qq group:573283836

apiVersion: v1
kind: PersistentVolume
metadata:
  name: myjdk-pv
  labels:
    app: myjdk-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - 10.1.11.201:6789
    pool: rbd
    image: myjdk-image
    user: admin
    secretRef:
      name: ceph-secret-key
    #keyring: "/etc/ceph/ceph.client.admin.keyring" 
    fsType: xfs
    readOnly: true
  #persistentVolumeReclaimPolicy: Recycle