# author:pengrk
# email:546711211@qq.com
# qq group:573283836

apiVersion: v1
kind: Service
metadata:
  name: rediss-db
  labels:
    name: rediss-db
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis-db
---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-db
spec:
  serviceName: rediss-db
  replicas: 1
  template: 
    metadata:
      name: redis-db
      labels:
        app: redis-db
    spec:
      hostNetwork: true
      nodeSelector:
        #zoneMgDb: "1"
        kubernetes.io/hostname: "10.1.12.28"
      containers:
      - name: redis-db
        imagePullPolicy: IfNotPresent
        image: 10.1.12.61:5000/redis:4.0.2
        ports:
        - containerPort: 6379
          hostPort: 6379
        volumeMounts:
        - name: host-persistent-storage
          mountPath: /usr/local/redis/
          readOnly: false
      volumes:
      - name: host-persistent-storage
        #emptyDir: {}
        hostPath:
         path: /redisData/data/

     

