# author:pengrk
# email:546711211@qq.com
# qq group:573283836

apiVersion: v1
kind: Service
metadata:
  name: nexus3-service
  labels:
    name: nexus3-service
spec:
  clusterIP: None
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: nexus3
---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nexus3
spec:
  serviceName: nexus3
  replicas: 1
  template: 
    metadata:
      name: nexus3
      labels:
        app: nexus3
    spec:
      hostNetwork: true
      nodeSelector:
        #zoneMgDb: "1"
        kubernetes.io/hostname: "10.1.12.28"
      containers:
      - name: nexus3
        imagePullPolicy: IfNotPresent
        image: 10.1.12.61:5000/nexus3
        ports:
        - containerPort: 8081
          hostPort: 8081
        volumeMounts:
        - name: host-persistent-storage
          mountPath: /nexus-data
          readOnly: false
      volumes:
      - name: host-persistent-storage
        #emptyDir: {}
        hostPath:
         path: /nexusData/data/

     

