#https://github.com/kubernetes/ingress/blob/master/examples/tcp/nginx/nginx-tcp-ingress-controller.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-tcp-ingress-lb
  labels:
    name: nginx-tcp-ingress-lb
  namespace: kube-system
spec:
  template:
    metadata:
      labels:       
        name: nginx-tcp-ingress-lb
    spec:
      serviceAccountName: ingress
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      nodeSelector:
        ingress: haproxy    
      containers:
      - image: 10.1.11.60:5000/nginx-ingress-controller:0.9.0-beta.7
        name: nginx-tcp-ingress-lb
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 9000
          hostPort: 9000
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --tcp-services-configmap=$(POD_NAMESPACE)/nginx-tcp-ingress-configmap